import Link from "next/link";
import { PageFrame } from "./components/page-frame";

export default function HomePage() {
  return (
    <PageFrame>
      <main>
        <section className="hero-section">
          <div className="hero-copy">
            <p className="eyebrow">Digital health infrastructure for real-world care</p>
            <h1 id="hero-heading">Healthcare access, connected.</h1>
            <p className="lede">Danmante connects patients, verified healthcare professionals, and certified pharmacies through secure digital workflows designed around local laws and professional scope.</p>
            <div className="cta-row"><Link href="/patient" className="button primary">Find care</Link><Link href="/nurse" className="button secondary">Join as a nurse</Link><Link href="/pharmacy" className="text-link">Register a pharmacy <span aria-hidden="true">-&gt;</span></Link></div>
            <p className="safety-note"><strong>Safety first.</strong> Danmante is not an emergency service. Contact local emergency services immediately in a medical emergency.</p>
          </div>
          <div className="hero-visual" aria-label="Illustration of connected healthcare pathways" role="img"><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" /><div className="visual-core"><span>care</span><strong>connected</strong></div><div className="visual-node node-one">Patient</div><div className="visual-node node-two">Nurse</div><div className="visual-node node-three">Pharmacy</div></div>
        </section>

        <section className="section-block" id="how-it-works" aria-labelledby="how-heading"><div className="section-heading"><p className="eyebrow">A clearer path to care</p><h2 id="how-heading">Designed around the moments that matter.</h2><p>One connected workflow, with safety checks at every meaningful handoff.</p></div><div className="steps-grid"><article><span className="step-number">01</span><h3>Find care</h3><p>Discover available professionals and care pathways that match your needs and supported location.</p></article><article><span className="step-number">02</span><h3>Consult securely</h3><p>Use a structured consultation workflow with clear boundaries around access, identity, and privacy.</p></article><article><span className="step-number">03</span><h3>Receive guidance</h3><p>Professional review remains central. Scope and jurisdiction rules govern what can happen next.</p></article><article><span className="step-number">04</span><h3>Connect to a pharmacy</h3><p>Where legally and clinically appropriate, eligible referrals can move to certified pharmacy workflows.</p></article></div></section>

        <section className="audience-section" aria-labelledby="audience-heading"><div className="section-heading"><p className="eyebrow">One platform, distinct needs</p><h2 id="audience-heading">Built for the people inside the care journey.</h2></div><div className="audience-grid"><Link href="/patient" className="audience-card patient-card"><span className="card-kicker">For patients</span><h3>Care that starts with understanding.</h3><p>Find professionals, request a consultation, manage follow-up, and understand when local rules affect availability.</p><span className="card-arrow" aria-hidden="true">-&gt;</span></Link><Link href="/nurse" className="audience-card nurse-card"><span className="card-kicker">For nurses</span><h3>A professional workspace with guardrails.</h3><p>Prepare for credential review, manage availability, and support consultations within verified scope.</p><span className="card-arrow" aria-hidden="true">-&gt;</span></Link><Link href="/pharmacy" className="audience-card pharmacy-card"><span className="card-kicker">For pharmacies</span><h3>More context for safer fulfillment.</h3><p>Prepare for pharmacy and pharmacist verification, eligible referrals, review, and fulfillment workflows.</p><span className="card-arrow" aria-hidden="true">-&gt;</span></Link></div></section>

        <section className="trust-section" aria-labelledby="trust-heading"><div className="trust-copy"><p className="eyebrow">Trust is a workflow</p><h2 id="trust-heading">Verification before visibility.</h2><p>Danmante is designed so identity, credentials, licenses, and jurisdiction are part of the access model, not an afterthought.</p><Link href="/safety" className="button secondary">Explore safety and verification</Link></div><div className="trust-list"><div><strong>Professional identity</strong><span>Prepared for identity and credential review.</span></div><div><strong>License and scope</strong><span>Care actions remain bounded by applicable authorization.</span></div><div><strong>Pharmacy readiness</strong><span>Business and pharmacist checks belong before fulfillment.</span></div></div></section>

        <section className="payment-section" aria-labelledby="payment-heading"><div><p className="eyebrow">Flexible payments, carefully separated</p><h2 id="payment-heading">Payment choice should never change clinical safety.</h2></div><p>Danmante can be prepared for cards and compatible digital wallets, including Celo ecosystem rails where legally and technically appropriate. Payment data stays separate from clinical information. Medical records, diagnoses, prescriptions, and PHI do not belong on-chain.</p></section>

        <section className="faq-section" aria-labelledby="faq-heading"><div className="section-heading"><p className="eyebrow">Common questions</p><h2 id="faq-heading">Clear answers for an evolving platform.</h2></div><div className="faq-grid"><details><summary>Is Danmante available everywhere?</summary><p>No. Availability depends on local law, licensing, professional scope, and supported jurisdictions.</p></details><details><summary>Can Danmante prescribe medication?</summary><p>Danmante does not make a universal prescribing claim. Any clinical or pharmacy action must be permitted by the applicable jurisdiction and authorized professional.</p></details><details><summary>Is this an emergency service?</summary><p>No. Contact local emergency services immediately if you are experiencing a medical emergency.</p></details><details><summary>Is the platform live today?</summary><p>This repository contains a buildable foundation and public website. Production authentication, verification, payment, and clinical workflows require further engineering and external review.</p></details></div></section>

        <section className="final-cta"><p className="eyebrow">Build the next layer of access</p><h2>Healthcare access, connected.</h2><p>Start with the role that brings you to Danmante. The platform will tell you what is ready, what is prepared, and what still needs review.</p><div className="cta-row"><Link href="/patient" className="button primary">Find care</Link><Link href="/about" className="button light">Learn about Danmante</Link></div></section>
      </main>
    </PageFrame>
  );
}
